#!/usr/bin/env bash
# APERTURE-CLEAN pre-compact.sh
# Extracts systemic failures from transcript before /compact.

LEDGER="FAILURE_LEDGER.md"
MAX_SIZE=102400 # 100KB

log_stderr() {
  echo "$@" >&2
}

# Initialize ledger if empty or missing
if [[ ! -s "$LEDGER" ]]; then
  echo "# Persistent Failure Ledger" > "$LEDGER"
  echo "" >> "$LEDGER"
  echo "> Auto-generated by pre-compact.sh" >> "$LEDGER"
  echo "" >> "$LEDGER"
fi

# Temporary file for current session extractions
TEMP_FAILURES=$(mktemp)

# Read transcript and extract patterns
# Using a loop to handle each line of input
while IFS= read -r line; do
  if echo "$line" | grep -qiE "Error:|Failed:|Exception|exit code [1-9]|Permission denied|Access forbidden|blocked by rules|violates|NEVER|forbidden pattern"; then
    echo "$line" >> "$TEMP_FAILURES"
  fi
done

# Process extractions into structured entries
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  
  TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  TYPE="UNKNOWN"
  if echo "$line" | grep -qiE "error|failed|exception|exit"; then TYPE="TOOL_ERROR"; fi
  if echo "$line" | grep -qiE "permission|access|blocked"; then TYPE="PERMISSION"; fi
  if echo "$line" | grep -qiE "violates|NEVER|forbidden"; then TYPE="CONSTRAINT"; fi
  
  PATTERN=$(echo "$line" | tr -d '*`#' | head -c 100)
  CONTEXT="Transcript extraction"
  SEVERITY="MAJOR"
  
  # Deduplication check
  if grep -qF "$PATTERN" "$LEDGER"; then
    log_stderr "Duplicate pattern found: $PATTERN"
    continue
  fi

  cat >> "$LEDGER" <<EOF
---
**Timestamp:** $TIMESTAMP  
**Type:** $TYPE  
**Pattern:** $PATTERN  
**Context:** $CONTEXT  
**Severity:** $SEVERITY  
**Recurrence:** 1
---
EOF
done < "$TEMP_FAILURES"

rm -f "$TEMP_FAILURES"

echo "### APERTURE STATE EXTRACTION COMPLETE"
