#!/usr/bin/env bash
# .claude/hooks/pre-compact.sh
# PreCompact Hook — executes BEFORE context compaction wipes session memory
# Purpose: Extract critical state to filesystem so it survives the memory purge
# Trigger: Registered in .claude/settings.json → hooks.pre_compact
# Ref: Anthropic context engineering — "PreCompact hook" pattern

set -euo pipefail

# ────────────────────────────────────────────
# CONFIG
# ────────────────────────────────────────────
TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
SNAPSHOT_DIR=".claude/snapshots"
SNAPSHOT_FILE="${SNAPSHOT_DIR}/pre-compact-${TIMESTAMP}.md"
SESSION_JSONL="${CLAUDE_SESSION_JSONL:-}"   # injected by Claude Code runtime if available
TODO_PATTERN="TodoWrite|TODO:|FIXME:|BLOCKED:"
MODIFIED_FILES_CMD="git diff --name-only HEAD 2>/dev/null || echo '(git unavailable)'"

# ────────────────────────────────────────────
# SETUP
# ────────────────────────────────────────────
mkdir -p "${SNAPSHOT_DIR}"

echo "# Pre-Compact Snapshot — ${TIMESTAMP}" > "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"
echo "_Auto-generated by .claude/hooks/pre-compact.sh before context compaction._" >> "${SNAPSHOT_FILE}"
echo "_Read this file to restore task state after /clear or session restart._" >> "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"

# ────────────────────────────────────────────
# SECTION 1: MODIFIED FILES (git-based ground truth)
# ────────────────────────────────────────────
echo "## Modified Files (Uncommitted)" >> "${SNAPSHOT_FILE}"
echo '```' >> "${SNAPSHOT_FILE}"
eval "${MODIFIED_FILES_CMD}" >> "${SNAPSHOT_FILE}"
echo '```' >> "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"

# Staged files
echo "## Staged Files" >> "${SNAPSHOT_FILE}"
echo '```' >> "${SNAPSHOT_FILE}"
git diff --name-only --cached 2>/dev/null || echo "(none or git unavailable)" >> "${SNAPSHOT_FILE}"
echo '```' >> "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"

# ────────────────────────────────────────────
# SECTION 2: ACTIVE TODO / BLOCKED ITEMS
# Extract from session JSONL if available, else grep source tree
# ────────────────────────────────────────────
echo "## Active TODOs and Blockers" >> "${SNAPSHOT_FILE}"
echo '```' >> "${SNAPSHOT_FILE}"

if [[ -n "${SESSION_JSONL}" && -f "${SESSION_JSONL}" ]]; then
  # Extract TodoWrite tool calls from session log
  grep -o '"TodoWrite".*' "${SESSION_JSONL}" 2>/dev/null \
    | python3 -c "
import sys, json
for line in sys.stdin:
    try:
        obj = json.loads(line.strip().lstrip('\"TodoWrite\"').strip(','))
        if isinstance(obj, list):
            for item in obj:
                print(f\"[{item.get('status','?').upper()}] {item.get('content','')}\")
    except Exception:
        pass
" 2>/dev/null || echo "(could not parse session JSONL)"
else
  # Fallback: grep source tree for TODO markers
  grep -rn "${TODO_PATTERN}" \
    --include="*.ts" --include="*.tsx" --include="*.js" \
    --include="*.py" --include="*.go" --include="*.rs" \
    --include="*.md" \
    --exclude-dir=node_modules --exclude-dir=dist --exclude-dir=.git \
    . 2>/dev/null | head -40 || echo "(none found)"
fi

echo '```' >> "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"

# ────────────────────────────────────────────
# SECTION 3: RECENT GIT LOG (last 5 commits — orientation anchor)
# ────────────────────────────────────────────
echo "## Recent Commits" >> "${SNAPSHOT_FILE}"
echo '```' >> "${SNAPSHOT_FILE}"
git log --oneline -5 2>/dev/null || echo "(git unavailable)"
echo '```' >> "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"

# ────────────────────────────────────────────
# SECTION 4: CURRENT BRANCH
# ────────────────────────────────────────────
echo "## Current Branch" >> "${SNAPSHOT_FILE}"
echo '```' >> "${SNAPSHOT_FILE}"
git branch --show-current 2>/dev/null || echo "(git unavailable)"
echo '```' >> "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"

# ────────────────────────────────────────────
# SECTION 5: MANUAL PRESERVATION SLOT
# This section is intentionally empty — the /compact command's
# explicit preserve directives are appended here by the CLI runtime.
# ────────────────────────────────────────────
echo "## Explicitly Preserved Context" >> "${SNAPSHOT_FILE}"
echo "_Populated by: /compact preserve: [...] directives_" >> "${SNAPSHOT_FILE}"
echo "" >> "${SNAPSHOT_FILE}"

# ────────────────────────────────────────────
# DONE
# ────────────────────────────────────────────
echo "✓ Pre-compact snapshot saved → ${SNAPSHOT_FILE}"
echo "  Resume with: Read ${SNAPSHOT_FILE} and continue from active blockers."
